[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pentest-toolbox"
version = "0.1.0"
description = "A suite of various useful pentesting tools"
authors = [
    {name = "sparklehound", email = "your.email@example.com"}
]
license = {file = "LICENSE"}
dependencies = [
    "argparse",
    "click",
    "typer"
]
classifiers = [
    # Classifiers
]

[project.entry-points.console_scripts]
hello = "hello_world.main:main"
